In [52]:
import numpy as np
from scipy.spatial.distance import euclidean
from fastdtw import fastdtw

#5개의 학습 시계열 데이터
data = [
    np.array([[2,2], [3,3], [4,4], [5,5], [6,6]]),
    np.array([[1,1], [2,2], [3,3], [4,4], [3,5]]),
    np.array([[10,10], [9,9], [8,8], [7,7], [6,6]]),
    np.array([[1,2], [2,3], [3,4], [4,5], [5,6]]),
    np.array([[10,20], [20,30], [30,40], [40,50]]),
]

#데이터 간 DTW 거리 계산
dtw_distances = []
for i in range(len(data)):
    for j in range(i+1, len(data)):
        distance, path = fastdtw(data[i], data[j], dist=euclidean)
        dtw_distances.append(distance)

#평균, 분산
aver_dtw = np.mean(dtw_distances)
var_dtw = np.var(dtw_distances)
#학습 자료 생성
result = {'average': aver_dtw, 'variance': var_dtw} 

# 추가 인식용 시계열 데이터 3개
recog_series1 = np.array([[1,3], [2,4], [3,5], [4,6], [5,7]])
recog_series2 = np.array([[2,3], [3,4], [4,5], [5,6], [6,7]])
recog_series3= np.array([[5,5], [6,6], [7,7], [8,8], [9,9]])
#한 배열로 합침
recog_series = [recog_series1, recog_series2, recog_series3]

i = 1
for r_series in recog_series:
    recog_dtw = []
    paths = []
    for series in data:
        distance, path = fastdtw(r_series, series, dist=euclidean) #각 학습 데이터와 거리 계산
        recog_dtw.append(distance)
        paths.append(path)

    index = np.argmin(recog_dtw) #가장 가까운 데이터 인덱스
    closest_series = data[index]
    print(f"\n============{i}=============")
    print("인식용 시계열 자료:\n", r_series)
    print("비유사도: ", recog_dtw[index])
    print("대응 방향: ", paths[index])
    i+=1



============1=============
인식용 시계열 자료:
 [[1 3]
 [2 4]
 [3 5]
 [4 6]
 [5 7]]
비유사도:  5.0
대응 방향:  [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]

============2=============
인식용 시계열 자료:
 [[2 3]
 [3 4]
 [4 5]
 [5 6]
 [6 7]]
비유사도:  2.8284271247461903
대응 방향:  [(0, 0), (0, 1), (1, 2), (2, 3), (3, 4), (4, 4)]

============3=============
인식용 시계열 자료:
 [[5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]
비유사도:  16.970562748477143
대응 방향:  [(0, 0), (0, 1), (0, 2), (0, 3), (1, 4), (2, 4), (3, 4), (4, 4)]
